name: techgrains
description: Developer friendly app library having various commonly used functionality.
version: 1.6.9+1
homepage: https://github.com/techgrains/TGFramework-Flutter

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.20.2
  yaml: ^3.1.3
  shared_preferences: ^2.5.3
  http: ^1.5.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

# The following section is specific to Flutter.
flutter:

